import { Platform, StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const createStyles = (textScale = 1) =>
  StyleSheet.create({
    app: { flex: 1, backgroundColor: colors.page },
    screen: { flex: 1, backgroundColor: colors.page },
    content: { paddingHorizontal: 18, paddingTop: 6, paddingBottom: 98 },
    skeleton: { backgroundColor: colors.lavender, borderRadius: 8 },
    skeletonCircle: { borderRadius: 999 },
    skeletonGap: { marginTop: 8 },
    skeletonSearch: { marginBottom: 16, borderRadius: 14 },
    skeletonComposer: {
      minHeight: 93,
      borderRadius: 18,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      padding: 14,
      flexDirection: "row",
      marginBottom: 22,
    },
    skeletonComposerCopy: { flex: 1, marginLeft: 11, justifyContent: "center" },
    skeletonSectionTitle: { marginBottom: 11 },
    skeletonPostTop: { flexDirection: "row", alignItems: "center" },
    skeletonPostCopy: { flex: 1, marginLeft: 10 },
    skeletonPostLine: { marginTop: 19 },
    skeletonPostActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      borderTopWidth: 1,
      borderTopColor: colors.line,
      marginTop: 17,
      paddingTop: 12,
    },
    header: {
      height: 62,
      paddingHorizontal: 18,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    headerTitle: {
      position: "absolute",
      left: 78,
      right: 78,
      textAlign: "center",
      fontSize: 19,
      color: colors.ink,
      fontWeight: "800",
    },
    headerIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.white,
      justifyContent: "center",
      alignItems: "center",
    },
    badge: {
      position: "absolute",
      top: -3,
      right: -5,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: "#E78895",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.page,
    },
    badgeText: { color: colors.white, fontSize: 8, fontWeight: "800" },
    brand: { alignItems: "center", marginBottom: 18 },
    compactBrand: { marginBottom: 0, flexDirection: "row" },
    logo: { width: 76, height: 58, marginBottom: -8 },
    brandText: {
      color: colors.ink,
      fontSize: 26,
      fontWeight: "800",
      letterSpacing: -1.3,
    },
    brandDot: { color: colors.purple },
    authWrap: { flex: 1, backgroundColor: colors.lavender },
    authScroll: { flexGrow: 1, justifyContent: "center", padding: 22 },
    authWordmark: { alignSelf: "center", marginBottom: 16 },
    authGlass: {
      borderWidth: 1,
      borderRadius: 28,
      padding: 22,
      overflow: "hidden",
      shadowColor: "#4E4565",
      shadowOpacity: 0.16,
      shadowRadius: 26,
      shadowOffset: { width: 0, height: 14 },
      elevation: 6,
    },
    tag: {
      alignSelf: "flex-start",
      backgroundColor: colors.softPurple,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
      marginBottom: 14,
    },
    tagText: {
      color: colors.purpleDark,
      fontSize: 10,
      letterSpacing: 1,
      fontWeight: "800",
    },
    authTitle: {
      color: colors.ink,
      fontSize: 29,
      lineHeight: 34,
      letterSpacing: -0.8,
      fontWeight: "800",
      marginBottom: 10,
    },
    authSubtitle: {
      color: colors.muted,
      fontSize: 14 * textScale,
      lineHeight: 20,
      marginBottom: 24,
    },
    authFooter: {
      color: colors.purpleDark,
      textAlign: "center",
      marginTop: 22,
      fontSize: 13,
    },
    link: {
      color: colors.purpleDark,
      fontWeight: "800",
      textDecorationLine: "underline",
    },
    inputGroup: { marginBottom: 16 },
    inputLabel: {
      color: colors.ink,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 7,
    },
    inputShell: {
      minHeight: 49,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.input,
      borderRadius: 13,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 13,
    },
    input: { flex: 1, color: colors.ink, fontSize: 15 * textScale, paddingVertical: 10 },
    inputAction: {
      color: colors.purple,
      fontSize: 12,
      fontWeight: "800",
      paddingLeft: 8,
    },
    primaryButton: {
      height: 52,
      borderRadius: 14,
      backgroundColor: colors.purple,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      marginTop: 6,
    },
    primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: "800" },
    buttonEnd: { position: "absolute", right: 18 },
    disabled: { opacity: 0.58 },
    pressed: { opacity: 0.72, transform: [{ scale: 0.96 }] },
    inlineError: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.dangerSurface,
      borderRadius: 10,
      padding: 10,
      marginBottom: 12,
    },
    errorText: {
      flex: 1,
      color: colors.danger,
      fontSize: 12,
      marginLeft: 6,
      lineHeight: 17,
    },
    searchInput: { flex: 1, color: colors.ink, fontSize: 14 * textScale },
    composer: {
      flexDirection: "row",
      backgroundColor: colors.white,
      borderRadius: 18,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      marginBottom: 22,
    },
    composerBody: { flex: 1, marginLeft: 11 },
    composerInput: {
      minHeight: 50,
      color: colors.ink,
      fontSize: 15 * textScale,
      lineHeight: 21,
      textAlignVertical: "top",
      paddingTop: 0,
    },
    composerFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    composerImageWrap: { position: "relative", marginBottom: 12 },
    composerImage: {
      width: "100%",
      height: 180,
      borderRadius: 14,
      backgroundColor: colors.lavender,
    },
    composerImageRemove: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: "rgba(35,29,48,0.72)",
      alignItems: "center",
      justifyContent: "center",
    },
    composerMeta: { flexDirection: "row", alignItems: "center", gap: 10 },
    composerActions: { flexDirection: "row", alignItems: "center", gap: 9 },
    composerPhotoButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 6,
      paddingRight: 4,
    },
    composerPhotoText: { color: colors.purple, fontSize: 12, fontWeight: "800" },
    composerRecordingText: { color: colors.danger },
    composerVoiceDraft: { flexDirection: "row", alignItems: "center", gap: 8 },
    smallButton: {
      backgroundColor: colors.purple,
      height: 29,
      paddingHorizontal: 16,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
    },
    smallButtonText: { color: colors.white, fontSize: 12, fontWeight: "800" },
    titleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 11,
    },
    sectionTitle: {
      color: colors.ink,
      fontSize: 18 * textScale,
      fontWeight: "800",
      letterSpacing: -0.25,
    },
    mutedSmall: { color: colors.muted, fontSize: 11 * textScale, marginTop: 2 },
    card: {
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 18,
      padding: 15,
      marginBottom: 16,
    },
    postTop: { flexDirection: "row", alignItems: "center" },
    postAuthor: { flex: 1, marginLeft: 10 },
    postName: { color: colors.ink, fontSize: 14 * textScale, fontWeight: "800" },
    iconHit: { padding: 5 },
    postText: {
      color: colors.ink,
      fontSize: 16 * textScale,
      lineHeight: 23,
      fontWeight: "600",
      marginTop: 14,
    },
    postImage: {
      width: "100%",
      height: 220,
      borderRadius: 14,
      backgroundColor: colors.lavender,
      marginTop: 14,
    },
    photoViewerOverlay: { flex: 1, backgroundColor: "rgba(13, 10, 20, 0.97)" },
    photoViewerToolbar: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 18, paddingTop: 18 },
    photoViewerControl: { width: 42, height: 42, borderRadius: 21, backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" },
    photoViewerImageArea: { flex: 1, alignItems: "center", justifyContent: "center", padding: 18 },
    photoViewerImage: { width: "100%", height: "100%" },
    postActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 17,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.line,
    },
    inlineAction: { flexDirection: "row", alignItems: "center", gap: 5 },
    replyText: { color: colors.purple, fontSize: 12 * textScale, fontWeight: "800" },
    nav: {
      height: 67,
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      backgroundColor: colors.white,
      borderTopWidth: 1,
      borderColor: colors.line,
      paddingBottom: Platform.OS === "ios" ? 5 : 0,
    },
    navItem: { width: 74, alignItems: "center", paddingTop: 6 },
    navText: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "700",
      marginTop: 3,
    },
    activeNavText: { color: colors.purple },
    navBadge: {
      position: "absolute",
      top: -5,
      right: -11,
      minWidth: 15,
      height: 15,
      borderRadius: 8,
      backgroundColor: "#E78895",
      justifyContent: "center",
      alignItems: "center",
    },
    flex: { flex: 1 },
    personCopy: { marginLeft: 11 },
    divider: { borderBottomWidth: 1, borderColor: colors.line },
    searchPageInput: {
      minHeight: 52,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.white,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
      paddingHorizontal: 14,
      marginBottom: 22,
    },
    searchPrompt: { alignItems: "center", justifyContent: "center", paddingTop: 72, paddingHorizontal: 28 },
    searchPromptIcon: { width: 67, height: 67, borderRadius: 34, backgroundColor: colors.softPurple, alignItems: "center", justifyContent: "center", marginBottom: 15 },
    searchPromptTitle: { color: colors.ink, fontSize: 20 * textScale, fontWeight: "900", letterSpacing: -0.4 },
    searchPromptText: { color: colors.muted, fontSize: 13 * textScale, textAlign: "center", lineHeight: 19 * textScale, marginTop: 7 },
    searchSectionTitle: { color: colors.ink, fontSize: 16 * textScale, fontWeight: "900", marginBottom: 10, marginTop: 4 },
    searchPeopleCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 18, paddingHorizontal: 14, marginBottom: 22 },
    searchPersonRow: { minHeight: 73, flexDirection: "row", alignItems: "center" },
    searchUsername: { color: colors.muted, fontSize: 12 * textScale, marginTop: 3 },
    notificationHeading: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
      marginTop: 3,
    },
    readPill: {
      backgroundColor: colors.softPurple,
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 11,
    },
    readText: { color: colors.purpleDark, fontSize: 11, fontWeight: "800" },
    notification: { flexDirection: "row", paddingVertical: 15 },
    notificationCopy: { marginLeft: 11, paddingTop: 1 },
    notificationText: { color: colors.ink, fontSize: 13, lineHeight: 19 },
    dot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#E78895",
      position: "absolute",
      top: -1,
      right: -1,
      borderWidth: 2,
      borderColor: colors.white,
    },
    refreshButton: {
      flexDirection: "row",
      alignSelf: "center",
      alignItems: "center",
      gap: 7,
      backgroundColor: colors.softPurple,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    refreshText: { color: colors.purpleDark, fontSize: 12, fontWeight: "800" },
    settingsProfile: {
      backgroundColor: colors.lavender,
      borderRadius: 18,
      minHeight: 88,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 15,
      marginBottom: 25,
    },
    settingsProfileAction: { flexDirection: "row", alignItems: "center", gap: 4 },
    settingsProfileActionText: { color: colors.purple, fontSize: 12 * textScale, fontWeight: "800" },
    groupLabel: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.1,
      marginBottom: 8,
      marginLeft: 3,
    },
    setting: { minHeight: 74, flexDirection: "row", alignItems: "center", paddingVertical: 9 },
    settingIcon: {
      width: 33,
      height: 33,
      borderRadius: 10,
      backgroundColor: colors.softPurple,
      alignItems: "center",
      justifyContent: "center",
    },
    settingTitle: { color: colors.ink, fontSize: 13 * textScale, fontWeight: "800" },
    settingControl: {
      width: 46,
      minHeight: 44,
      marginLeft: 8,
      alignItems: "flex-end",
      justifyContent: "center",
      flexShrink: 0,
    },
    settingToggle: {
      width: 46,
      height: 26,
      padding: 3,
      borderRadius: 13,
      backgroundColor: colors.line,
      justifyContent: "flex-start",
      alignItems: "flex-start",
    },
    settingToggleOn: { backgroundColor: colors.purple },
    settingToggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
    },
    settingToggleThumbOn: { transform: [{ translateX: 20 }] },
    settingsInfo: {
      flexDirection: "row",
      gap: 10,
      alignItems: "flex-start",
      backgroundColor: colors.softPurple,
      borderRadius: 14,
      padding: 14,
      marginBottom: 22,
    },
    settingsInfoText: { flex: 1, color: colors.purpleDark, fontSize: 12 * textScale, lineHeight: 18 * textScale },
    resetButton: {
      minHeight: 65,
      borderWidth: 1,
      borderColor: colors.danger,
      backgroundColor: colors.dangerSurface,
      borderRadius: 14,
      paddingHorizontal: 15,
      marginBottom: 13,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    resetTitle: { color: colors.danger, fontSize: 13, fontWeight: "800" },
    logoutButton: {
      height: 51,
      borderWidth: 1,
      borderColor: colors.danger,
      backgroundColor: colors.dangerSurface,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    logoutText: { color: colors.danger, fontSize: 14, fontWeight: "800" },
    profileHero: { flexDirection: "row", alignItems: "center" },
    profileCopy: { marginLeft: 14 },
    profileName: {
      color: colors.ink,
      fontSize: 21 * textScale,
      letterSpacing: -0.4,
      fontWeight: "800",
    },
    followButton: {
      height: 35,
      paddingHorizontal: 16,
      borderRadius: 18,
      backgroundColor: colors.purple,
      justifyContent: "center",
      alignItems: "center",
    },
    followingButton: {
      backgroundColor: colors.softPurple,
      borderWidth: 1,
      borderColor: colors.line,
    },
    profileActions: { flexDirection: "row", alignItems: "center", gap: 7 },
    profileTools: {
      width: 35,
      height: 35,
      borderRadius: 18,
      backgroundColor: colors.softPurple,
      alignItems: "center",
      justifyContent: "center",
    },
    followText: { color: colors.white, fontSize: 12, fontWeight: "800" },
    followingText: { color: colors.purpleDark },
    bio: { color: colors.ink, fontSize: 13 * textScale, lineHeight: 19 * textScale, marginTop: 20 },
    stats: {
      height: 74,
      borderRadius: 16,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      marginTop: 21,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
    },
    stat: { alignItems: "center", flex: 1 },
    statValue: { color: colors.ink, fontSize: 18, fontWeight: "800" },
    statLine: { height: 29, width: 1, backgroundColor: colors.line },
    tabs: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderColor: colors.line,
      marginTop: 26,
      marginBottom: 15,
    },
    tab: {
      flex: 1,
      height: 38,
      alignItems: "center",
      justifyContent: "center",
      borderBottomWidth: 2,
      borderColor: "transparent",
    },
    activeTab: { borderColor: colors.purple },
    tabText: { color: colors.muted, fontSize: 12 * textScale, fontWeight: "700" },
    activeTabText: { color: colors.purple, fontWeight: "800" },
    skeletonProfileHero: { flexDirection: "row", alignItems: "center" },
    skeletonProfileCopy: { flex: 1, marginLeft: 14, justifyContent: "center" },
    skeletonPill: { borderRadius: 18 },
    skeletonBio: { marginTop: 24 },
    skeletonStats: {
      height: 74,
      borderRadius: 16,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      marginTop: 21,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
    },
    skeletonTabs: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      height: 54,
      borderBottomWidth: 1,
      borderColor: colors.line,
      marginBottom: 15,
    },
    empty: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 30,
      gap: 9,
    },
    emptyText: { color: colors.muted, fontSize: 13, textAlign: "center" },
    overlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(35, 29, 48, 0.38)",
    },
    dismiss: { flex: 1 },
    sheet: {
      height: "75%",
      minHeight: 420,
      backgroundColor: colors.white,
      borderRadius: 27,
      marginHorizontal: 12,
      marginBottom: 12,
      paddingHorizontal: 18,
      overflow: "hidden",
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: "#594E72",

    },
  
    handle: {
      alignSelf: "center",
      width: 38,
      height: 4,
      borderRadius: 3,
      backgroundColor: colors.line,
      marginTop: 9,
    },
    sheetHeader: {
      height: 57,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sheetTitle: { color: colors.ink, fontSize: 18, fontWeight: "800" },
    close: {
      width: 31,
      height: 31,
      borderRadius: 16,
      backgroundColor: colors.softPurple,
      justifyContent: "center",
      alignItems: "center",
    },
    question: {
      flexDirection: "row",
      backgroundColor: colors.input,
      borderRadius: 14,
      padding: 12,
      marginBottom: 4,
    },
    questionCopy: { marginLeft: 10 },
    questionText: {
      color: colors.ink,
      fontSize: 12 * textScale,
      lineHeight: 17,
      fontWeight: "600",
      marginTop: 4,
    },
    questionImage: {
      width: "100%",
      height: 160,
      borderRadius: 10,
      backgroundColor: colors.lavender,
      marginTop: 9,
    },
    responses: { flex: 1 },
    responsesContent: { paddingVertical: 6 },
    response: { flexDirection: "row", paddingVertical: 12 },
    responseCopy: { marginLeft: 10 },
    responseTop: { flexDirection: "row", alignItems: "baseline", gap: 6 },
    responseBody: {
      color: colors.ink,
      fontSize: 13 * textScale,
      lineHeight: 18,
      marginTop: 4,
    },
    replyComposer: {
      borderTopWidth: 1,
      borderColor: colors.line,
      paddingVertical: 9,
      gap: 8,
    },
    recordingIndicator: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 3,
    },
    recordingText: { color: colors.danger, fontSize: 12, fontWeight: "800" },
    voiceDraft: { flexDirection: "row", alignItems: "center", gap: 8 },
    voiceDiscard: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.softPurple,
      alignItems: "center",
      justifyContent: "center",
    },
    voiceMessage: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      minWidth: 145,
      maxWidth: "100%",
      gap: 9,
      backgroundColor: colors.input,
      borderRadius: 15,
      paddingVertical: 7,
      paddingHorizontal: 8,
      marginTop: 8,
    },
    voicePlay: {
      width: 29,
      height: 29,
      borderRadius: 15,
      backgroundColor: colors.purple,
      alignItems: "center",
      justifyContent: "center",
    },
    voiceProgress: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.line,
      overflow: "hidden",
    },
    voiceProgressFill: { height: "100%", backgroundColor: colors.purple },
    voiceWaveform: { flex: 1, height: 20, flexDirection: "row", alignItems: "center", gap: 2 },
    voiceWaveBar: { width: 3, borderRadius: 2, backgroundColor: colors.purple },
    voiceSpeed: {
      minWidth: 28,
      height: 23,
      borderRadius: 12,
      backgroundColor: colors.softPurple,
      alignItems: "center",
      justifyContent: "center",
    },
    voiceSpeedText: { color: colors.purpleDark, fontSize: 10, fontWeight: "800" },
    voiceDuration: { color: colors.muted, fontSize: 11, fontWeight: "700" },
    replyInput: {
      minHeight: 64,
      flexDirection: "row",
      alignItems: "center",
    },
    replyTextInput: {
      flex: 1,
      minHeight: 39,
      maxHeight: 75,
      borderRadius: 17,
      backgroundColor: colors.input,
      color: colors.ink,
      marginLeft: 9,
      paddingHorizontal: 13,
      paddingVertical: 9,
      fontSize: 13 * textScale,
    },
    voiceRecord: {
      width: 35,
      height: 35,
      borderRadius: 18,
      backgroundColor: colors.softPurple,
      marginLeft: 7,
      alignItems: "center",
      justifyContent: "center",
    },
    voiceRecording: { backgroundColor: colors.danger },
    send: {
      width: 35,
      height: 35,
      borderRadius: 18,
      backgroundColor: colors.purple,
      marginLeft: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    editorSheet: {
      minHeight: 265,
      backgroundColor: colors.white,
      borderRadius: 27,
      marginHorizontal: 12,
      marginBottom: 12,
      paddingHorizontal: 18,
      paddingBottom: 25,
      overflow: "hidden",
    },
    editorInput: {
      minHeight: 105,
      borderRadius: 14,
      backgroundColor: colors.input,
      color: colors.ink,
      padding: 14,
      fontSize: 15,
      textAlignVertical: "top",
    },
    editorImage: {
      width: "100%",
      height: 130,
      borderRadius: 14,
      backgroundColor: colors.lavender,
      marginTop: 12,
    },
    editorAttachmentActions: { flexDirection: "row", alignItems: "center", gap: 7 },
    editorMediaButton: {
      width: 35,
      height: 35,
      borderRadius: 18,
      backgroundColor: colors.softPurple,
      alignItems: "center",
      justifyContent: "center",
    },
    editorMediaButtonRecording: { backgroundColor: colors.danger },
    profileEditorAvatar: { alignSelf: "center", position: "relative", marginBottom: 17 },
    profileEditorCamera: {
      position: "absolute",
      right: -2,
      bottom: -2,
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.purple,
      borderWidth: 2,
      borderColor: colors.white,
      alignItems: "center",
      justifyContent: "center",
    },
    profileEditorInput: {
      minHeight: 45,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.input,
      color: colors.ink,
      paddingHorizontal: 12,
      fontSize: 14,
      marginBottom: 12,
    },
    profileEditorBio: {
      minHeight: 72,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.input,
      color: colors.ink,
      padding: 12,
      fontSize: 14,
      textAlignVertical: "top",
      marginBottom: 12,
    },
    editorFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 13,
    },
    errorBar: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 18,
      minHeight: 52,
      borderRadius: 14,
      backgroundColor: "#4F4660",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
      elevation: 7,
    },
    errorBarText: {
      color: colors.white,
      fontSize: 12,
      lineHeight: 17,
      flex: 1,
    },
    system: {
      flex: 1,
      backgroundColor: colors.lavender,
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
    },
    systemCard: {
      width: "100%",
      maxWidth: 380,
      backgroundColor: colors.white,
      borderRadius: 24,
      padding: 24,
      alignItems: "center",
      gap: 13,
    },
    systemTitle: { color: colors.ink, fontSize: 21, fontWeight: "800" },
    systemText: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 20,
      textAlign: "center",
    },
    onboardingOverlay: {
      flex: 1,
      backgroundColor: colors.lavender,
      justifyContent: "center",
      padding: 20,
      overflow: "hidden",
    },
    onboardingBackdropOrbOne: {
      position: "absolute",
      width: 290,
      height: 290,
      borderRadius: 145,
      backgroundColor: colors.softPurple,
      top: -110,
      right: -95,
      opacity: 0.76,
    },
    onboardingBackdropOrbTwo: {
      position: "absolute",
      width: 230,
      height: 230,
      borderRadius: 115,
      backgroundColor: colors.white,
      bottom: -104,
      left: -95,
      opacity: 0.52,
    },
    onboardingCard: {
      backgroundColor: colors.white,
      borderRadius: 30,
      padding: 20,
      maxWidth: 430,
      width: "100%",
      alignSelf: "center",
      overflow: "hidden",
      shadowColor: "#43385A",
      shadowOpacity: 0.18,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 15 },
      elevation: 7,
    },
    onboardingTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    onboardingWordmark: { flexDirection: "row", alignItems: "center", gap: 6 },
    onboardingWordmarkDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.purple },
    onboardingWordmarkText: { color: colors.ink, fontSize: 17, fontWeight: "900", letterSpacing: -0.7 },
    onboardingSkipButton: { minHeight: 34, justifyContent: "center", paddingHorizontal: 11, borderRadius: 17, backgroundColor: colors.input },
    onboardingSkipButtonText: { color: colors.purpleDark, fontSize: 12, fontWeight: "800" },
    onboardingStepBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 14, backgroundColor: colors.softPurple },
    onboardingStepBadgeText: { color: colors.purpleDark, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
    onboardingHero: {
      height: 151,
      borderRadius: 23,
      backgroundColor: colors.purple,
      overflow: "hidden",
      marginTop: 18,
      padding: 18,
      justifyContent: "space-between",
    },
    onboardingHeroOrbOne: { position: "absolute", width: 155, height: 155, borderRadius: 78, backgroundColor: colors.white, opacity: 0.13, top: -58, right: -33 },
    onboardingHeroOrbTwo: { position: "absolute", width: 115, height: 115, borderRadius: 58, backgroundColor: colors.white, opacity: 0.1, bottom: -46, left: 74 },
    onboardingHeroOrbit: { width: 72, height: 72, borderRadius: 36, backgroundColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
    onboardingIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.white,
      alignItems: "center",
      justifyContent: "center",
    },
    onboardingHeroCopy: { alignItems: "flex-start" },
    onboardingHeroLabel: { color: "rgba(255,255,255,0.73)", fontSize: 9, fontWeight: "900", letterSpacing: 1.05 },
    onboardingHeroTitle: { color: "#FFFFFF", fontSize: 20, letterSpacing: -0.5, fontWeight: "900", marginTop: 4 },
    onboardingEyebrow: { alignSelf: "flex-start", backgroundColor: colors.softPurple, borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5, marginTop: 20 },
    onboardingEyebrowText: { color: colors.purpleDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.9 },
    onboardingTitle: { color: colors.ink, fontSize: 25, lineHeight: 30, letterSpacing: -0.8, fontWeight: "900", marginTop: 12 },
    onboardingText: { color: colors.muted, fontSize: 14 * textScale, lineHeight: 21 * textScale, marginTop: 9 },
    onboardingDetail: { minHeight: 48, borderRadius: 14, backgroundColor: colors.input, flexDirection: "row", alignItems: "center", paddingHorizontal: 11, marginTop: 18 },
    onboardingDetailIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.softPurple, alignItems: "center", justifyContent: "center", marginRight: 9 },
    onboardingDetailText: { flex: 1, color: colors.purpleDark, fontSize: 12 * textScale, fontWeight: "700" },
    onboardingProgressRow: { flexDirection: "row", alignItems: "center", gap: 11, marginTop: 22, marginBottom: 15 },
    onboardingProgressCount: { color: colors.ink, fontSize: 11, fontWeight: "900", letterSpacing: 0.2 },
    onboardingProgressTotal: { color: colors.muted },
    onboardingProgressTrack: { flex: 1, height: 6, borderRadius: 3, backgroundColor: colors.line, overflow: "hidden" },
    onboardingProgressFill: { height: "100%", borderRadius: 3, backgroundColor: colors.purple },
    onboardingActions: { flexDirection: "row", gap: 10, alignItems: "center" },
    onboardingBackButton: { width: 50, height: 50, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.input, alignItems: "center", justifyContent: "center" },
    onboardingBackPlaceholder: { width: 50, height: 50 },
    onboardingPrimaryButton: { flex: 1, height: 50, borderRadius: 16, backgroundColor: colors.purple, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, shadowColor: colors.purple, shadowOpacity: 0.26, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
    onboardingPrimaryButtonText: { color: colors.white, fontSize: 14, fontWeight: "900" },
    onboardingFootnote: { color: colors.muted, textAlign: "center", fontSize: 11 * textScale, marginTop: 15 },
  });
