import { Platform, StyleSheet } from "react-native";
import { colors } from "../constants/theme";

export const createStyles = () =>
  StyleSheet.create({
    app: { flex: 1, backgroundColor: colors.page },
    screen: { flex: 1, backgroundColor: colors.page },
    content: { paddingHorizontal: 18, paddingTop: 6, paddingBottom: 98 },
    skeleton: { backgroundColor: colors.lavender, borderRadius: 8 },
    skeletonCircle: { borderRadius: 999 },
    skeletonGap: { marginTop: 8 },
    skeletonSearch: { marginBottom: 16, borderRadius: 14 },
    skeletonComposer: {
      minHeight: 93,
      borderRadius: 18,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      padding: 14,
      flexDirection: "row",
      marginBottom: 22,
    },
    skeletonComposerCopy: { flex: 1, marginLeft: 11, justifyContent: "center" },
    skeletonSectionTitle: { marginBottom: 11 },
    skeletonPostTop: { flexDirection: "row", alignItems: "center" },
    skeletonPostCopy: { flex: 1, marginLeft: 10 },
    skeletonPostLine: { marginTop: 19 },
    skeletonPostActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      borderTopWidth: 1,
      borderTopColor: colors.line,
      marginTop: 17,
      paddingTop: 12,
    },
    header: {
      height: 62,
      paddingHorizontal: 18,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    headerTitle: {
      position: "absolute",
      left: 78,
      right: 78,
      textAlign: "center",
      fontSize: 19,
      color: colors.ink,
      fontWeight: "800",
    },
    headerIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.white,
      justifyContent: "center",
      alignItems: "center",
    },
    badge: {
      position: "absolute",
      top: -3,
      right: -5,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: "#E78895",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.page,
    },
    badgeText: { color: colors.white, fontSize: 8, fontWeight: "800" },
    brand: { alignItems: "center", marginBottom: 18 },
    compactBrand: { marginBottom: 0, flexDirection: "row" },
    logo: { width: 76, height: 58, marginBottom: -8 },
    brandText: {
      color: colors.ink,
      fontSize: 26,
      fontWeight: "800",
      letterSpacing: -1.3,
    },
    brandDot: { color: colors.purple },
    authWrap: { flex: 1, backgroundColor: colors.lavender },
    authScroll: { flexGrow: 1, justifyContent: "center", padding: 22 },
    authCard: {
      backgroundColor: colors.white,
      borderRadius: 27,
      padding: 24,
      shadowColor: "#594E72",
      shadowOpacity: 0.11,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 10 },
      elevation: 3,
    },
    tag: {
      alignSelf: "flex-start",
      backgroundColor: colors.softPurple,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
      marginBottom: 14,
    },
    tagText: {
      color: colors.purpleDark,
      fontSize: 10,
      letterSpacing: 1,
      fontWeight: "800",
    },
    authTitle: {
      color: colors.ink,
      fontSize: 29,
      lineHeight: 34,
      letterSpacing: -0.8,
      fontWeight: "800",
      marginBottom: 10,
    },
    authSubtitle: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 24,
    },
    authFooter: {
      color: colors.purpleDark,
      textAlign: "center",
      marginTop: 22,
      fontSize: 13,
    },
    link: {
      color: colors.purpleDark,
      fontWeight: "800",
      textDecorationLine: "underline",
    },
    inputGroup: { marginBottom: 16 },
    inputLabel: {
      color: colors.ink,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 7,
    },
    inputShell: {
      minHeight: 49,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.input,
      borderRadius: 13,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 13,
    },
    input: { flex: 1, color: colors.ink, fontSize: 15, paddingVertical: 10 },
    inputAction: {
      color: colors.purple,
      fontSize: 12,
      fontWeight: "800",
      paddingLeft: 8,
    },
    primaryButton: {
      height: 52,
      borderRadius: 14,
      backgroundColor: colors.purple,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      marginTop: 6,
    },
    primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: "800" },
    buttonEnd: { position: "absolute", right: 18 },
    disabled: { opacity: 0.58 },
    inlineError: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.dangerSurface,
      borderRadius: 10,
      padding: 10,
      marginBottom: 12,
    },
    errorText: {
      flex: 1,
      color: colors.danger,
      fontSize: 12,
      marginLeft: 6,
      lineHeight: 17,
    },
    search: {
      height: 46,
      borderWidth: 1,
      borderColor: colors.line,
      backgroundColor: colors.white,
      borderRadius: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      marginBottom: 16,
    },
    searchInput: { flex: 1, color: colors.ink, fontSize: 14 },
    composer: {
      flexDirection: "row",
      backgroundColor: colors.white,
      borderRadius: 18,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      marginBottom: 22,
    },
    composerBody: { flex: 1, marginLeft: 11 },
    composerInput: {
      minHeight: 50,
      color: colors.ink,
      fontSize: 15,
      lineHeight: 21,
      textAlignVertical: "top",
      paddingTop: 0,
    },
    composerFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    composerImageWrap: { position: "relative", marginBottom: 12 },
    composerImage: {
      width: "100%",
      height: 180,
      borderRadius: 14,
      backgroundColor: colors.lavender,
    },
    composerImageRemove: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: "rgba(35,29,48,0.72)",
      alignItems: "center",
      justifyContent: "center",
    },
    composerMeta: { flexDirection: "row", alignItems: "center", gap: 10 },
    composerPhotoButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 6,
      paddingRight: 4,
    },
    composerPhotoText: { color: colors.purple, fontSize: 12, fontWeight: "800" },
    smallButton: {
      backgroundColor: colors.purple,
      height: 29,
      paddingHorizontal: 16,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
    },
    smallButtonText: { color: colors.white, fontSize: 12, fontWeight: "800" },
    titleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 11,
    },
    sectionTitle: {
      color: colors.ink,
      fontSize: 18,
      fontWeight: "800",
      letterSpacing: -0.25,
    },
    mutedSmall: { color: colors.muted, fontSize: 11, marginTop: 2 },
    card: {
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 18,
      padding: 15,
      marginBottom: 16,
    },
    postTop: { flexDirection: "row", alignItems: "center" },
    postAuthor: { flex: 1, marginLeft: 10 },
    postName: { color: colors.ink, fontSize: 14, fontWeight: "800" },
    iconHit: { padding: 5 },
    postText: {
      color: colors.ink,
      fontSize: 16,
      lineHeight: 23,
      fontWeight: "600",
      marginTop: 14,
    },
    postImage: {
      width: "100%",
      height: 220,
      borderRadius: 14,
      backgroundColor: colors.lavender,
      marginTop: 14,
    },
    postActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 17,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.line,
    },
    inlineAction: { flexDirection: "row", alignItems: "center", gap: 5 },
    replyText: { color: colors.purple, fontSize: 12, fontWeight: "800" },
    nav: {
      height: 67,
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      backgroundColor: colors.white,
      borderTopWidth: 1,
      borderColor: colors.line,
      paddingBottom: Platform.OS === "ios" ? 5 : 0,
    },
    navItem: { width: 74, alignItems: "center", paddingTop: 6 },
    navText: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "700",
      marginTop: 3,
    },
    activeNavText: { color: colors.purple },
    navBadge: {
      position: "absolute",
      top: -5,
      right: -11,
      minWidth: 15,
      height: 15,
      borderRadius: 8,
      backgroundColor: "#E78895",
      justifyContent: "center",
      alignItems: "center",
    },
    hero: {
      backgroundColor: colors.lavender,
      borderRadius: 19,
      padding: 21,
      marginBottom: 24,
    },
    kicker: {
      color: colors.purpleDark,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.5,
      marginBottom: 8,
    },
    heroTitle: {
      color: colors.ink,
      fontSize: 25,
      lineHeight: 29,
      letterSpacing: -0.7,
      fontWeight: "800",
      marginBottom: 8,
    },
    heroSub: { color: colors.ink, fontSize: 13, lineHeight: 19, maxWidth: 260 },
    trend: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 13,
      borderBottomWidth: 1,
      borderColor: colors.line,
    },
    trendNumber: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: "800",
      width: 32,
    },
    flex: { flex: 1 },
    trendTag: { color: colors.ink, fontSize: 15, fontWeight: "800" },
    personRow: { minHeight: 76, flexDirection: "row", alignItems: "center" },
    personCopy: { marginLeft: 11 },
    divider: { borderBottomWidth: 1, borderColor: colors.line },
    viewPill: {
      borderWidth: 1.25,
      borderColor: colors.purple,
      height: 31,
      minWidth: 57,
      paddingHorizontal: 9,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    viewText: { color: colors.purple, fontSize: 11, fontWeight: "800" },
    notificationHeading: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
      marginTop: 3,
    },
    readPill: {
      backgroundColor: colors.softPurple,
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 11,
    },
    readText: { color: colors.purpleDark, fontSize: 11, fontWeight: "800" },
    notification: { flexDirection: "row", paddingVertical: 15 },
    notificationCopy: { marginLeft: 11, paddingTop: 1 },
    notificationText: { color: colors.ink, fontSize: 13, lineHeight: 19 },
    dot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#E78895",
      position: "absolute",
      top: -1,
      right: -1,
      borderWidth: 2,
      borderColor: colors.white,
    },
    refreshButton: {
      flexDirection: "row",
      alignSelf: "center",
      alignItems: "center",
      gap: 7,
      backgroundColor: colors.softPurple,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    refreshText: { color: colors.purpleDark, fontSize: 12, fontWeight: "800" },
    settingsProfile: {
      backgroundColor: colors.lavender,
      borderRadius: 18,
      minHeight: 88,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 15,
      marginBottom: 25,
    },
    groupLabel: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.1,
      marginBottom: 8,
      marginLeft: 3,
    },
    setting: { minHeight: 70, flexDirection: "row", alignItems: "center" },
    settingIcon: {
      width: 33,
      height: 33,
      borderRadius: 10,
      backgroundColor: colors.softPurple,
      alignItems: "center",
      justifyContent: "center",
    },
    settingTitle: { color: colors.ink, fontSize: 13, fontWeight: "800" },
    settingControl: {
      width: 52,
      minHeight: 44,
      marginLeft: 12,
      alignItems: "flex-end",
      justifyContent: "center",
      flexShrink: 0,
    },
    settingToggle: {
      width: 46,
      height: 26,
      padding: 3,
      borderRadius: 13,
      backgroundColor: colors.line,
      justifyContent: "center",
    },
    settingToggleOn: { backgroundColor: colors.purple },
    settingToggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
    },
    settingToggleThumbOn: { alignSelf: "flex-end" },
    resetButton: {
      minHeight: 65,
      borderWidth: 1,
      borderColor: colors.danger,
      backgroundColor: colors.dangerSurface,
      borderRadius: 14,
      paddingHorizontal: 15,
      marginBottom: 13,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    resetTitle: { color: colors.danger, fontSize: 13, fontWeight: "800" },
    logoutButton: {
      height: 51,
      borderWidth: 1,
      borderColor: colors.danger,
      backgroundColor: colors.dangerSurface,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    logoutText: { color: colors.danger, fontSize: 14, fontWeight: "800" },
    profileHero: { flexDirection: "row", alignItems: "center" },
    profileCopy: { marginLeft: 14 },
    profileName: {
      color: colors.ink,
      fontSize: 21,
      letterSpacing: -0.4,
      fontWeight: "800",
    },
    followButton: {
      height: 35,
      paddingHorizontal: 16,
      borderRadius: 18,
      backgroundColor: colors.purple,
      justifyContent: "center",
      alignItems: "center",
    },
    followingButton: {
      backgroundColor: colors.softPurple,
      borderWidth: 1,
      borderColor: colors.line,
    },
    followText: { color: colors.white, fontSize: 12, fontWeight: "800" },
    followingText: { color: colors.purpleDark },
    bio: { color: colors.ink, fontSize: 13, lineHeight: 19, marginTop: 20 },
    stats: {
      height: 74,
      borderRadius: 16,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      marginTop: 21,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
    },
    stat: { alignItems: "center", flex: 1 },
    statValue: { color: colors.ink, fontSize: 18, fontWeight: "800" },
    statLine: { height: 29, width: 1, backgroundColor: colors.line },
    tabs: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderColor: colors.line,
      marginTop: 26,
      marginBottom: 15,
    },
    tab: {
      flex: 1,
      height: 38,
      alignItems: "center",
      justifyContent: "center",
      borderBottomWidth: 2,
      borderColor: "transparent",
    },
    activeTab: { borderColor: colors.purple },
    tabText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
    activeTabText: { color: colors.purple, fontWeight: "800" },
    skeletonProfileHero: { flexDirection: "row", alignItems: "center" },
    skeletonProfileCopy: { flex: 1, marginLeft: 14, justifyContent: "center" },
    skeletonPill: { borderRadius: 18 },
    skeletonBio: { marginTop: 24 },
    skeletonStats: {
      height: 74,
      borderRadius: 16,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.line,
      marginTop: 21,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
    },
    skeletonTabs: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      height: 54,
      borderBottomWidth: 1,
      borderColor: colors.line,
      marginBottom: 15,
    },
    empty: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 30,
      gap: 9,
    },
    emptyText: { color: colors.muted, fontSize: 13, textAlign: "center" },
    overlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(35, 29, 48, 0.38)",
    },
    dismiss: { flex: 1 },
    sheet: {
      height: "75%",
      minHeight: 420,
      backgroundColor: colors.white,
      borderRadius: 27,
      marginHorizontal: 12,
      marginBottom: 12,
      paddingHorizontal: 18,
      overflow: "hidden",
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: "#594E72",

    },
  
    handle: {
      alignSelf: "center",
      width: 38,
      height: 4,
      borderRadius: 3,
      backgroundColor: colors.line,
      marginTop: 9,
    },
    sheetHeader: {
      height: 57,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sheetTitle: { color: colors.ink, fontSize: 18, fontWeight: "800" },
    close: {
      width: 31,
      height: 31,
      borderRadius: 16,
      backgroundColor: colors.softPurple,
      justifyContent: "center",
      alignItems: "center",
    },
    question: {
      flexDirection: "row",
      backgroundColor: colors.input,
      borderRadius: 14,
      padding: 12,
      marginBottom: 4,
    },
    questionCopy: { marginLeft: 10 },
    questionText: {
      color: colors.ink,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: "600",
      marginTop: 4,
    },
    questionImage: {
      width: "100%",
      height: 160,
      borderRadius: 10,
      backgroundColor: colors.lavender,
      marginTop: 9,
    },
    responses: { flex: 1 },
    responsesContent: { paddingVertical: 6 },
    response: { flexDirection: "row", paddingVertical: 12 },
    responseCopy: { marginLeft: 10 },
    responseTop: { flexDirection: "row", alignItems: "baseline", gap: 6 },
    responseBody: {
      color: colors.ink,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 4,
    },
    replyInput: {
      minHeight: 64,
      paddingVertical: 9,
      borderTopWidth: 1,
      borderColor: colors.line,
      flexDirection: "row",
      alignItems: "center",
    },
    replyTextInput: {
      flex: 1,
      minHeight: 39,
      maxHeight: 75,
      borderRadius: 17,
      backgroundColor: colors.input,
      color: colors.ink,
      marginLeft: 9,
      paddingHorizontal: 13,
      paddingVertical: 9,
      fontSize: 13,
    },
    send: {
      width: 35,
      height: 35,
      borderRadius: 18,
      backgroundColor: colors.purple,
      marginLeft: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    editorSheet: {
      minHeight: 265,
      backgroundColor: colors.white,
      borderRadius: 27,
      marginHorizontal: 12,
      marginBottom: 12,
      paddingHorizontal: 18,
      paddingBottom: 25,
      overflow: "hidden",
    },
    editorInput: {
      minHeight: 105,
      borderRadius: 14,
      backgroundColor: colors.input,
      color: colors.ink,
      padding: 14,
      fontSize: 15,
      textAlignVertical: "top",
    },
    editorFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 13,
    },
    errorBar: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 18,
      minHeight: 52,
      borderRadius: 14,
      backgroundColor: "#4F4660",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
      elevation: 7,
    },
    errorBarText: {
      color: colors.white,
      fontSize: 12,
      lineHeight: 17,
      flex: 1,
    },
    system: {
      flex: 1,
      backgroundColor: colors.lavender,
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
    },
    systemCard: {
      width: "100%",
      maxWidth: 380,
      backgroundColor: colors.white,
      borderRadius: 24,
      padding: 24,
      alignItems: "center",
      gap: 13,
    },
    systemTitle: { color: colors.ink, fontSize: 21, fontWeight: "800" },
    systemText: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 20,
      textAlign: "center",
    },
  });
